version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - 9100:9100
    volumes:
          - /proc:/host/proc
          - /sys:/host/sys
          - /:/rootfs
  sample-app-1:
    build:
      context: ./sample-app/original
      dockerfile: ./Dockerfile
    container_name: sample-app-1
    ports:
      - 8081:8080
  sample-app-2:
    build:
      context: ./sample-app/original
      dockerfile: ./Dockerfile
    container_name: sample-app-2
    ports:
      - 8082:8080
  sample-app-3:
    build:
      context: ./sample-app/original
      dockerfile: ./Dockerfile
    container_name: sample-app-3
    ports:
      - 8083:8080
