global:   
  scrape_interval: 10s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: 
        - prometheus:9090
  - job_name: node-exporter
    static_configs:
      - targets:
        - node-exporter:9100
  - job_name: sample-app
    static_configs:
      - targets:
        - sample-app-1:8080
        - sample-app-2:8080
        - sample-app-3:8080
